source /etc/profile.d/rvm.sh
gem install builder
gem install bundler
gem install god
gem install fastimage
gem install diff-lcs
gem install json
gem install term-ansicolor
gem install curb
gem install mime-types
gem install nokogiri
gem install open4
gem install rack
gem install redis
gem install redis-namespace
gem install tilt
gem install sinatra
gem install vegas
gem install resque
gem install rspec-core
gem install rspec-expectations
gem install rspec-mocks
gem install rspec
gem install rubyzip
gem install streamio-ffmpeg
gem install trollop
gem install gherkin
gem install cucumber
